spring:
  application:
    # Never use '_' in application name
    # Use '-' instead
    # Otherwise gateway may not work correctly
    name: services

  config:
    import: configserver:http://localhost:8888
